import { populateAbraLine } from './abra-line.js';
import { populateBellsproutLine } from './bellsprout-line.js';
import { populateBulbasaurLine } from './bulbasaur-line.js';
import { populateCaterpieLine } from './caterpie-line.js';
import { populateCharmanderLine } from './charmander-line.js';
import { populateClefairyLine } from './clefairy-line.js';
import { populateCuboneLine } from './cubone-line.js';
import { populateDiglettLine } from './diglett-line..js';
import { populateDoduoLine } from './doduo-line.js';
import { populateDrowzeeLine } from './drowzee-line.js';
import { populateEkansLine } from './ekans-line.js';
import { populateExeggcuteLine } from './exeggcute-line.js';
import { populateGastlyLine } from './gastly-line.js';
import { populateGeodudeLine } from './geodude-line.js';
import { populateGoldeenLine } from './goldeen-line.js';
import { populateGrimerLine } from './grimer-line.js';
import { populateGrowlitheLine } from './growlithe-line.js';
import { populateHorseaLine } from './horsea-line.js';
import { populateKoffingLine } from './koffing-line.js';
import { populateKrabbyLine } from './krabby-line.js';
import { populateMachopLine } from './machop-line.js';
import { populateMagnemiteLine } from './magnemite-line.js';
import { populateMankeyLine } from './mankey-line.js';
import { populateMeowthLine } from './meowth-line.js';
import { populateNidoranFLine } from './Nidoran♀-line.js';
import { populateNidoranMLine } from './nidoran♂-line.js';
import { populateOddishLine } from './oddish-line.js';
import { populateParasLine } from './paras-line.js';
import { populatePidgeyLine } from './pidgey-line.js';
import { populatePikachuLine } from './pikachu-line.js';
import { populatePoliwagLine } from './poliwag-line.js';
import { populatePonytaLine } from './ponyta-line.js';
import { populatePsyduckLine } from './psyduck-line.js';
import { populateRattataLine } from './rattata-line.js';
import { populateRhyhornLine } from './rhyhorn-line.js';
import { populateSandshrewLine } from './sandshrew-line.js';
import { populateSeelLine } from './seel-line.js';
import { populateShellderLine } from './shellder-line.js';
import { populateSlowpokeLine } from './slowpoke-line.js';
import { populateSpearowLine } from './spearow-line.js';
import { populateSquirtleLine } from './squirtle-line.js';
import { populateStaryuLine } from './staryu-line.js';
import { populateTentacoolLine } from './tentacool-line.js';
import { populateVenonatLine } from './venonat-line.js';
import { populateVoltorbLine } from './voltorb-line.js';
import { populateVulpixLine } from './vulpix-line.js';
import { populateWeedleLine } from './weedle-line.js';
import { populateZubatLine } from './zubat-line.js';

export const populateGenIEvos = async () => {
  let count = 0;

  count += await populateBulbasaurLine();
  count += await populateCharmanderLine();
  count += await populateSquirtleLine();
  count += await populateCaterpieLine();
  count += await populateWeedleLine();
  count += await populatePidgeyLine();
  count += await populateRattataLine();
  count += await populateSpearowLine();
  count += await populateEkansLine();
  count += await populatePikachuLine();
  count += await populateSandshrewLine();
  count += await populateNidoranFLine();
  count += await populateNidoranMLine();
  count += await populateClefairyLine();
  count += await populateVulpixLine();
  count += await populateZubatLine();
  count += await populateOddishLine();
  count += await populateParasLine();
  count += await populateVenonatLine();
  count += await populateDiglettLine();
  count += await populateMeowthLine();
  count += await populatePsyduckLine();
  count += await populateMankeyLine();
  count += await populateGrowlitheLine();
  count += await populatePoliwagLine();
  count += await populateAbraLine();
  count += await populateMachopLine();
  count += await populateBellsproutLine();
  count += await populateTentacoolLine();
  count += await populateGeodudeLine();
  count += await populatePonytaLine();
  count += await populateSlowpokeLine();
  count += await populateMagnemiteLine();
  count += await populateDoduoLine();
  count += await populateSeelLine();
  count += await populateGrimerLine();
  count += await populateShellderLine();
  count += await populateGastlyLine();
  count += await populateDrowzeeLine();
  count += await populateKrabbyLine();
  count += await populateVoltorbLine();
  count += await populateExeggcuteLine();
  count += await populateCuboneLine();
  count += await populateKoffingLine();
  count += await populateRhyhornLine();
  count += await populateHorseaLine();
  count += await populateGoldeenLine();
  count += await populateStaryuLine();

  return count;
}